// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sightseeingStand.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sightseeingStand_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sightseeingStand_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sightseeingStand_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sightseeingStand_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sightseeingStand_2eproto;
namespace pb {
class SBroadSightSeeing;
class SBroadSightSeeingDefaultTypeInternal;
extern SBroadSightSeeingDefaultTypeInternal _SBroadSightSeeing_default_instance_;
}  // namespace pb
PROTOBUF_NAMESPACE_OPEN
template<> ::pb::SBroadSightSeeing* Arena::CreateMaybeMessage<::pb::SBroadSightSeeing>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace pb {

// ===================================================================

class SBroadSightSeeing :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:pb.SBroadSightSeeing) */ {
 public:
  SBroadSightSeeing();
  virtual ~SBroadSightSeeing();

  SBroadSightSeeing(const SBroadSightSeeing& from);
  SBroadSightSeeing(SBroadSightSeeing&& from) noexcept
    : SBroadSightSeeing() {
    *this = ::std::move(from);
  }

  inline SBroadSightSeeing& operator=(const SBroadSightSeeing& from) {
    CopyFrom(from);
    return *this;
  }
  inline SBroadSightSeeing& operator=(SBroadSightSeeing&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SBroadSightSeeing& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SBroadSightSeeing* internal_default_instance() {
    return reinterpret_cast<const SBroadSightSeeing*>(
               &_SBroadSightSeeing_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SBroadSightSeeing& a, SBroadSightSeeing& b) {
    a.Swap(&b);
  }
  inline void Swap(SBroadSightSeeing* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SBroadSightSeeing* New() const final {
    return CreateMaybeMessage<SBroadSightSeeing>(nullptr);
  }

  SBroadSightSeeing* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SBroadSightSeeing>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SBroadSightSeeing& from);
  void MergeFrom(const SBroadSightSeeing& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SBroadSightSeeing* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "pb.SBroadSightSeeing";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sightseeingStand_2eproto);
    return ::descriptor_table_sightseeingStand_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAngleFieldNumber = 1,
    kIntervalFieldNumber = 2,
  };
  // float angle = 1;
  void clear_angle();
  float angle() const;
  void set_angle(float value);
  private:
  float _internal_angle() const;
  void _internal_set_angle(float value);
  public:

  // int32 interval = 2;
  void clear_interval();
  ::PROTOBUF_NAMESPACE_ID::int32 interval() const;
  void set_interval(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_interval() const;
  void _internal_set_interval(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:pb.SBroadSightSeeing)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  float angle_;
  ::PROTOBUF_NAMESPACE_ID::int32 interval_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sightseeingStand_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SBroadSightSeeing

// float angle = 1;
inline void SBroadSightSeeing::clear_angle() {
  angle_ = 0;
}
inline float SBroadSightSeeing::_internal_angle() const {
  return angle_;
}
inline float SBroadSightSeeing::angle() const {
  // @@protoc_insertion_point(field_get:pb.SBroadSightSeeing.angle)
  return _internal_angle();
}
inline void SBroadSightSeeing::_internal_set_angle(float value) {
  
  angle_ = value;
}
inline void SBroadSightSeeing::set_angle(float value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:pb.SBroadSightSeeing.angle)
}

// int32 interval = 2;
inline void SBroadSightSeeing::clear_interval() {
  interval_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SBroadSightSeeing::_internal_interval() const {
  return interval_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SBroadSightSeeing::interval() const {
  // @@protoc_insertion_point(field_get:pb.SBroadSightSeeing.interval)
  return _internal_interval();
}
inline void SBroadSightSeeing::_internal_set_interval(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  interval_ = value;
}
inline void SBroadSightSeeing::set_interval(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_interval(value);
  // @@protoc_insertion_point(field_set:pb.SBroadSightSeeing.interval)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sightseeingStand_2eproto
